In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
data = pd.read_csv(r"D:\all ml projects\Mental Health Dataset.csv")

In [3]:
data.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [4]:
data.isna().sum()

Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
self_employed              5202
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

In [5]:
data['self_employed'] = data['self_employed'].fillna('Unknown')

In [6]:
data.isna().sum()

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64

In [7]:
data.drop('Timestamp', axis=1, inplace=True)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Gender                   292364 non-null  str
 1   Country                  292364 non-null  str
 2   Occupation               292364 non-null  str
 3   self_employed            292364 non-null  str
 4   family_history           292364 non-null  str
 5   treatment                292364 non-null  str
 6   Days_Indoors             292364 non-null  str
 7   Growing_Stress           292364 non-null  str
 8   Changes_Habits           292364 non-null  str
 9   Mental_Health_History    292364 non-null  str
 10  Mood_Swings              292364 non-null  str
 11  Coping_Struggles         292364 non-null  str
 12  Work_Interest            292364 non-null  str
 13  Social_Weakness          292364 non-null  str
 14  mental_health_interview  292364 non-null  str
 15  care_options             292364 non-null  str
dtypes: str(16)
memory usage: 35.7 MB

In [9]:
data.columns = data.columns.str.lower()

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gender                   292364 non-null  str
 1   country                  292364 non-null  str
 2   occupation               292364 non-null  str
 3   self_employed            292364 non-null  str
 4   family_history           292364 non-null  str
 5   treatment                292364 non-null  str
 6   days_indoors             292364 non-null  str
 7   growing_stress           292364 non-null  str
 8   changes_habits           292364 non-null  str
 9   mental_health_history    292364 non-null  str
 10  mood_swings              292364 non-null  str
 11  coping_struggles         292364 non-null  str
 12  work_interest            292364 non-null  str
 13  social_weakness          292364 non-null  str
 14  mental_health_interview  292364 non-null  str
 15  care_options             292364 non-null  str
dtypes: str(16)
memory usage: 35.7 MB

In [11]:
data['days_indoors'].unique()

<StringArray>
[         '1-14 days',   'Go out Every day', 'More than 2 months',
         '15-30 days',         '31-60 days']
Length: 5, dtype: str

In [12]:
data['days_indoors'] = pd.Categorical(
    data['days_indoors'],
    categories = [
        'Go out Every day',  
        '1-14 days',
        '15-30 days',
        '31-60 days',
        'More than 2 months'
    ],
    ordered=True
)

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gender                   292364 non-null  str
 1   country                  292364 non-null  str
 2   occupation               292364 non-null  str
 3   self_employed            292364 non-null  str
 4   family_history           292364 non-null  str
 5   treatment                292364 non-null  str
 6   days_indoors             292364 non-null  category
 7   growing_stress           292364 non-null  str
 8   changes_habits           292364 non-null  str
 9   mental_health_history    292364 non-null  str
 10  mood_swings              292364 non-null  str
 11  coping_struggles         292364 non-null  str
 12  work_interest            292364 non-null  str
 13  social_weakness          292364 non-null  str
 14  mental_health_interview  292364 non-null  str
 15  care_options             292364 non-null  str
dtypes: category(1), str(15)
memory usage: 33.7 MB

In [14]:
for col in data.columns:
    print(col + '-'*40)
    print(data[col].unique())
    print('*'*100)

gender----------------------------------------
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
****************************************************************************************************
country----------------------------------------
<StringArray>
[         'United States',                 'Poland',              'Australia',
                 'Canada',         'United Kingdom',           'South Africa',
                 'Sweden',            'New Zealand',            'Netherlands',
                  'India',                'Belgium',                'Ireland',
                 'France',               'Portugal',                 'Brazil',
             'Costa Rica',                 'Russia',                'Germany',
            'Switzerland',                'Finland',                 'Israel',
                  'Italy', 'Bosnia and Herzegovina',              'Singapore',
                'Nigeria',                'Croatia',               'Thailand',
                'Denmark',                 'Mexico',                 'Greece',
                'Moldova',               'Colombia',                'Georgia',
         'Czech Republic',            'Philippines']
Length: 35, dtype: str
****************************************************************************************************
occupation----------------------------------------
<StringArray>
['Corporate', 'Student', 'Business', 'Housewife', 'Others']
Length: 5, dtype: str
****************************************************************************************************
self_employed----------------------------------------
<StringArray>
['Unknown', 'No', 'Yes']
Length: 3, dtype: str
****************************************************************************************************
family_history----------------------------------------
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
****************************************************************************************************
treatment----------------------------------------
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
****************************************************************************************************
days_indoors----------------------------------------
['1-14 days', 'Go out Every day', 'More than 2 months', '15-30 days', '31-60 days']
Categories (5, str): ['Go out Every day' < '1-14 days' < '15-30 days' < '31-60 days' < 'More than 2 months']
****************************************************************************************************
growing_stress----------------------------------------
<StringArray>
['Yes', 'No', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
changes_habits----------------------------------------
<StringArray>
['No', 'Yes', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
mental_health_history----------------------------------------
<StringArray>
['Yes', 'No', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
mood_swings----------------------------------------
<StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str
****************************************************************************************************
coping_struggles----------------------------------------
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
****************************************************************************************************
work_interest----------------------------------------
<StringArray>
['No', 'Maybe', 'Yes']
Length: 3, dtype: str
****************************************************************************************************
social_weakness----------------------------------------
<StringArray>
['Yes', 'No', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
mental_health_interview----------------------------------------
<StringArray>
['No', 'Maybe', 'Yes']
Length: 3, dtype: str
****************************************************************************************************
care_options----------------------------------------
<StringArray>
['Not sure', 'No', 'Yes']
Length: 3, dtype: str
****************************************************************************************************

In [15]:
for col in data.columns:
    if len(data[col].unique())==2:
        print(col)
        print(data[col].unique())
        print('--------------------------------')

gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
--------------------------------
family_history
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------
treatment
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------
coping_struggles
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------

In [16]:
data['treatment'] = data['treatment'].map({'Yes':0, 'No':1})

for col in data.columns:
    if col != 'treatment' and data[col].nunique()==2:
        unique_val = data[col].unique()
        data[col]=data[col].map({unique_val[0]:0, unique_val[1]:1  })

In [17]:
data.head()

,gender,country,occupation,self_employed,family_history,treatment,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options
0,Female,United States,Corporate,Unknown,No,0,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,Female,United States,Corporate,Unknown,Yes,0,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,Female,United States,Corporate,Unknown,Yes,0,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,Female,United States,Corporate,No,Yes,0,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,Female,United States,Corporate,No,Yes,0,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()

In [20]:
data['days_indoors'] = data['days_indoors'].cat.codes

🧠 Encoding Types Cheat Sheet

1. Nominal
- Meaning: Just categories, no order
- Examples:
  - country (Nepal, India)
  - occupation (doctor, engineer)
- Methods:
  - LabelEncoder
  - (One-Hot Encoding — optional, but often preferred)

2. Ordinal
- Meaning: Has order / ranking
- Examples:
  - days_indoors (1-14 < 15-30 < 31-60)
  - mood (low < medium < high)
- Methods:
  - map()
  - pd.Categorical + .cat.codes

3. Binary
- Meaning: Only 2 values
- Examples:
  - Yes / No
  - Male / Female
- Methods:
  - map({'No': 0, 'Yes': 1})
  - LabelEncoder

In [21]:
data.head()

,gender,country,occupation,self_employed,family_history,treatment,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options
0,Female,United States,Corporate,Unknown,No,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,Female,United States,Corporate,Unknown,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,No
2,Female,United States,Corporate,Unknown,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,Female,United States,Corporate,No,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,Female,United States,Corporate,No,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [22]:
data.gender.unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [23]:
data['gender'] = le.fit_transform(data['gender'])

In [24]:
for col in data.columns:
    print(col + '-'*40)
    print(data[col].unique())
    print('*'*100)

gender----------------------------------------
[0 1]
****************************************************************************************************
country----------------------------------------
<StringArray>
[         'United States',                 'Poland',              'Australia',
                 'Canada',         'United Kingdom',           'South Africa',
                 'Sweden',            'New Zealand',            'Netherlands',
                  'India',                'Belgium',                'Ireland',
                 'France',               'Portugal',                 'Brazil',
             'Costa Rica',                 'Russia',                'Germany',
            'Switzerland',                'Finland',                 'Israel',
                  'Italy', 'Bosnia and Herzegovina',              'Singapore',
                'Nigeria',                'Croatia',               'Thailand',
                'Denmark',                 'Mexico',                 'Greece',
                'Moldova',               'Colombia',                'Georgia',
         'Czech Republic',            'Philippines']
Length: 35, dtype: str
****************************************************************************************************
occupation----------------------------------------
<StringArray>
['Corporate', 'Student', 'Business', 'Housewife', 'Others']
Length: 5, dtype: str
****************************************************************************************************
self_employed----------------------------------------
<StringArray>
['Unknown', 'No', 'Yes']
Length: 3, dtype: str
****************************************************************************************************
family_history----------------------------------------
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
****************************************************************************************************
treatment----------------------------------------
[0 1]
****************************************************************************************************
days_indoors----------------------------------------
[1 0 4 2 3]
****************************************************************************************************
growing_stress----------------------------------------
<StringArray>
['Yes', 'No', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
changes_habits----------------------------------------
<StringArray>
['No', 'Yes', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
mental_health_history----------------------------------------
<StringArray>
['Yes', 'No', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
mood_swings----------------------------------------
<StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str
****************************************************************************************************
coping_struggles----------------------------------------
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
****************************************************************************************************
work_interest----------------------------------------
<StringArray>
['No', 'Maybe', 'Yes']
Length: 3, dtype: str
****************************************************************************************************
social_weakness----------------------------------------
<StringArray>
['Yes', 'No', 'Maybe']
Length: 3, dtype: str
****************************************************************************************************
mental_health_interview----------------------------------------
<StringArray>
['No', 'Maybe', 'Yes']
Length: 3, dtype: str
****************************************************************************************************
care_options----------------------------------------
<StringArray>
['Not sure', 'No', 'Yes']
Length: 3, dtype: str
****************************************************************************************************

In [25]:
data.head()

,gender,country,occupation,self_employed,family_history,treatment,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options
0,0,United States,Corporate,Unknown,No,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,0,United States,Corporate,Unknown,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,No
2,0,United States,Corporate,Unknown,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,0,United States,Corporate,No,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,0,United States,Corporate,No,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [26]:
X= data.drop('treatment', axis=1)

In [27]:
y = data['treatment']

for cols in X.columns:
    if X[cols].nunique() == 2:
        print (cols)
        print('*'*100)

cols = [ 'gender', 'family_history', 'coping_struggles' ]

for i in cols:
    data[i] = le.fit_transform(data[i])

In [28]:
data.head()

,gender,country,occupation,self_employed,family_history,treatment,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options
0,0,United States,Corporate,Unknown,No,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,0,United States,Corporate,Unknown,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,No
2,0,United States,Corporate,Unknown,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,0,United States,Corporate,No,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,0,United States,Corporate,No,Yes,0,1,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [29]:
col = ['gender', 'days_indoors']
for cols in X.columns:
    if cols not in col:
        le = LabelEncoder()
        X[cols] = le.fit_transform(X[cols])

In [30]:
X.head()

,gender,country,occupation,self_employed,family_history,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options
0,0,34,1,1,0,1,2,1,2,2,0,1,2,1,1
1,0,34,1,1,1,1,2,1,2,2,0,1,2,1,0
2,0,34,1,1,1,1,2,1,2,2,0,1,2,1,2
3,0,34,1,0,1,1,2,1,2,2,0,1,2,0,2
4,0,34,1,0,1,1,2,1,2,2,0,1,2,1,2

In [31]:
y

0         0
1         0
2         0
3         0
4         0
         ..
292359    0
292360    0
292361    1
292362    0
292363    0
Name: treatment, Length: 292364, dtype: int64

In [32]:
X

,gender,country,occupation,self_employed,family_history,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options
0,0,34,1,1,0,1,2,1,2,2,0,1,2,1,1
1,0,34,1,1,1,1,2,1,2,2,0,1,2,1,0
2,0,34,1,1,1,1,2,1,2,2,0,1,2,1,2
3,0,34,1,0,1,1,2,1,2,2,0,1,2,0,2
4,0,34,1,0,1,1,2,1,2,2,0,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292359,1,34,0,2,1,2,1,0,1,1,1,1,0,0,1
292360,1,29,0,0,1,2,1,0,1,1,1,1,0,1,2
292361,1,34,0,0,1,2,1,0,1,1,1,1,0,1,0
292362,1,34,0,0,1,2,1,0,1,1,1,1,0,1,2
292363,1,34,0,0,1,2,1,0,1,1,1,1,0,1,2

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [36]:
mdl_names = {
    "lr": LogisticRegression(),
    "knn": KNeighborsClassifier(),
    #"nb": GaussianNB(),
    #"svm": SVC(),
    "rf": RandomForestClassifier(),
    "dt": DecisionTreeClassifier()
}

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
for name, models in mdl_names.items():
    models.fit(X_train, y_train)
    y_pred = models.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Accuracy score using model ({name}): {acc}")
    if name == 'dt':
        joblib.dump(models, 'Mental_Health_Project.pkl')
        joblib.dump(le, 'Label_Encoder.pkl')
    print("_"*100)

Accuracy score using model (lr): 0.7031792451216801
____________________________________________________________________________________________________
Accuracy score using model (knn): 0.6737981632548355
____________________________________________________________________________________________________
Accuracy score using model (rf): 0.7379303268175055
____________________________________________________________________________________________________
Accuracy score using model (dt): 0.7497135430027534
____________________________________________________________________________________________________